# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blaster.ui'
#
# Created: Tue Sep 23 14:40:21 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(962, 815)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MV Boli"))
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 925, 818))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(670, 800))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 651, 671))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 30, 600, 150))
        self.plainTextEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 180, 601, 61))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Filesystem-folder-grey-open-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 240, 395, 66))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_5.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_6, 2, 1, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_7.setMinimumSize(QtCore.QSize(230, 0))
        self.comboBox_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.gridLayout_5.addWidget(self.comboBox_7, 1, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 240, 120, 60))
        self.pushButton_3.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_3.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_3.addWidget(self.groupBox)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 684, 301))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(10, 5, 5, 5)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_6 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.label = QtGui.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_7 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.comboBox = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_14 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_8 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_16)
        self.comboBox_9 = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_9.setEnabled(True)
        self.comboBox_9.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_9)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_17)
        self.comboBox_10 = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_10.setEnabled(True)
        self.comboBox_10.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboBox_10)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_9 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_19 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_10 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_2)
        self.checkBox = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.checkBox)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 681, 321))
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 30, 600, 150))
        self.plainTextEdit_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 180, 601, 60))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.layoutWidget_3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_6.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget_3)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_6.addWidget(self.line_5, 1, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_6.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 240, 381, 71))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 2, 0, 1, 1)
        self.comboBox_11 = QtGui.QComboBox(self.layoutWidget_5)
        self.comboBox_11.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_11, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 2, 3, 1, 1)
        self.comboBox_12 = QtGui.QComboBox(self.layoutWidget_5)
        self.comboBox_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.gridLayout_7.addWidget(self.comboBox_12, 1, 2, 1, 2)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 240, 120, 60))
        self.pushButton_4.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_4.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 631, 300))
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 30, 600, 150))
        self.plainTextEdit_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 200, 120, 60))
        self.pushButton_5.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_5.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.layoutWidget_7 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 200, 371, 101))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_7)
        self.gridLayout_9.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.spinBox = QtGui.QSpinBox(self.layoutWidget_7)
        self.spinBox.setEnabled(True)
        self.spinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_9.addWidget(self.spinBox, 2, 3, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget_7)
        self.comboBox_2.setEnabled(True)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_2, 2, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget_7)
        self.label_21.setEnabled(True)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_9.addWidget(self.label_20, 1, 0, 1, 1)
        self.comboBox_14 = QtGui.QComboBox(self.layoutWidget_7)
        self.comboBox_14.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.gridLayout_9.addWidget(self.comboBox_14, 1, 2, 1, 2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 631, 321))
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.plainTextEdit_5 = QtGui.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(10, 30, 600, 150))
        self.plainTextEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_5.setObjectName(_fromUtf8("plainTextEdit_5"))
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 180, 601, 61))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_8.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.layoutWidget_6)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_8.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.layoutWidget_6)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_8.addWidget(self.line_6, 1, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget_6)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_8.addWidget(self.line_7, 1, 1, 1, 1)
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 240, 381, 52))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_2, 0, 0, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 240, 120, 60))
        self.pushButton_6.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_6.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 631, 311))
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox_6.setAutoFillBackground(False)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.plainTextEdit_6 = QtGui.QPlainTextEdit(self.groupBox_6)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(10, 30, 600, 150))
        self.plainTextEdit_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_6.setObjectName(_fromUtf8("plainTextEdit_6"))
        self.layoutWidget_8 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 180, 601, 59))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget_8)
        self.gridLayout_10.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButton_9.setMaximumSize(QtCore.QSize(150, 50))
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_10.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.layoutWidget_8)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_10.addWidget(self.line_8, 1, 0, 1, 1)
        self.line_9 = QtGui.QFrame(self.layoutWidget_8)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_10.addWidget(self.line_9, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 240, 351, 52))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_4 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_2.addWidget(self.radioButton_4, 0, 0, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_2.addWidget(self.radioButton_3, 1, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab_6)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 250, 120, 60))
        self.pushButton_7.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_7.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tableWidget = QtGui.QTableWidget(self.tab_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 791, 291))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.tab_5)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 320, 221, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Action-db-add-icon2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon1)
        self.commandLinkButton.setIconSize(QtCore.QSize(48, 48))
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.tab_5)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(20, 380, 185, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Action-db-remove-icon2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon2)
        self.commandLinkButton_2.setIconSize(QtCore.QSize(48, 48))
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuSequences = QtGui.QMenu(self.menubar)
        self.menuSequences.setObjectName(_fromUtf8("menuSequences"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear_all = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionClear_all.setFont(font)
        self.actionClear_all.setObjectName(_fromUtf8("actionClear_all"))
        self.actionAbout = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionDocumentation.setFont(font)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionConvert_Fasta_Excel = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionConvert_Fasta_Excel.setFont(font)
        self.actionConvert_Fasta_Excel.setObjectName(_fromUtf8("actionConvert_Fasta_Excel"))
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSequences.addAction(self.actionClear_all)
        self.menuSequences.addSeparator()
        self.menubar.addAction(self.menuSequences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BlasterQt", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#55aaff;\">                   BlasterQt</span></p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow", "Paste Query Sequence(s) in Plain Text or Fasta format", None))
        self.label_6.setText(_translate("MainWindow", "No file selected.", None))
        self.pushButton.setText(_translate("MainWindow", "Open File", None))
        self.label_7.setText(_translate("MainWindow", "Choose Database", None))
        self.label_8.setText(_translate("MainWindow", "Program", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "blastn", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "blastp", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "blastx", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "tblastn", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "tblastx", None))
        self.pushButton_3.setText(_translate("MainWindow", "BLAST", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Advanced Settings", None))
        self.label_12.setText(_translate("MainWindow", "Espect treshold", None))
        self.lineEdit_6.setText(_translate("MainWindow", "1e-10", None))
        self.label.setText(_translate("MainWindow", "Minimum Percent Identity (%)", None))
        self.lineEdit.setText(_translate("MainWindow", "80", None))
        self.label_13.setText(_translate("MainWindow", "Wordsize", None))
        self.lineEdit_7.setText(_translate("MainWindow", "11", None))
        self.label_5.setText(_translate("MainWindow", "Strand", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "both", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "minus", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "plus", None))
        self.label_14.setText(_translate("MainWindow", "No of threads", None))
        self.lineEdit_8.setText(_translate("MainWindow", "1", None))
        self.label_16.setText(_translate("MainWindow", "Genetic code", None))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "1 Standard", None))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "2 Vertebrate Mitochondrial", None))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "3 Yeast Mitochondrial", None))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "4 Mold, Protozoan, and Coelocoel Mitochondrial", None))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "5 Invertebrate Mitochondrial", None))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "6 Ciliate Nuclear", None))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "9 Echinoderm Nuclear", None))
        self.comboBox_9.setItemText(7, _translate("MainWindow", "10 Euplotid Nuclear", None))
        self.comboBox_9.setItemText(8, _translate("MainWindow", "11 Bacterial and Plant Plastid", None))
        self.comboBox_9.setItemText(9, _translate("MainWindow", "12 Alternative yeast nuclear", None))
        self.comboBox_9.setItemText(10, _translate("MainWindow", "13 Ascidian Mitochondrial", None))
        self.comboBox_9.setItemText(11, _translate("MainWindow", "14 Flatworm Mitochondrial", None))
        self.comboBox_9.setItemText(12, _translate("MainWindow", "15 Blepharisma Nuclear", None))
        self.comboBox_9.setItemText(13, _translate("MainWindow", "16 Chlorophycean Mitochondrial", None))
        self.comboBox_9.setItemText(14, _translate("MainWindow", "21 Trematode Mitochondrial", None))
        self.comboBox_9.setItemText(15, _translate("MainWindow", "22 Scenedesmus Obliquus Mitochondrial", None))
        self.comboBox_9.setItemText(16, _translate("MainWindow", "23 Thraustochytrium Mitochondrial", None))
        self.label_17.setText(_translate("MainWindow", "Matrix", None))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "PAM30", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "PAM70", None))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "BLOSUM80", None))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "BLOSUM45", None))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "BLOSUM62", None))
        self.label_18.setText(_translate("MainWindow", "Gap open", None))
        self.lineEdit_9.setText(_translate("MainWindow", "5", None))
        self.label_19.setText(_translate("MainWindow", "Gap extension", None))
        self.lineEdit_10.setText(_translate("MainWindow", "2", None))
        self.label_2.setText(_translate("MainWindow", "Ungapped Alignment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Local BLAST", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Paste Query Sequence(s) in Plain Text or Fasta format (<1000bp per sequence)", None))
        self.label_11.setText(_translate("MainWindow", "No file selected.", None))
        self.pushButton_2.setText(_translate("MainWindow", "Open File", None))
        self.label_9.setText(_translate("MainWindow", "Choose Database", None))
        self.label_10.setText(_translate("MainWindow", "Missmatches", None))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "0", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "2", None))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "3", None))
        self.pushButton_4.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Bowtie Alignment", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Paste Id(s) seperated by new line (> ignored)", None))
        self.pushButton_5.setText(_translate("MainWindow", "Extract", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Beginning", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "End", None))
        self.label_21.setText(_translate("MainWindow", "Ignore characters", None))
        self.label_20.setText(_translate("MainWindow", "Choose Database", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Fasta Extractor", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Paste Query Sequence(s) in Plain Text or Fasta format", None))
        self.label_3.setText(_translate("MainWindow", "No file selected.", None))
        self.pushButton_8.setText(_translate("MainWindow", "Open File", None))
        self.radioButton_2.setText(_translate("MainWindow", "Reverse complement", None))
        self.radioButton.setText(_translate("MainWindow", "Reverse only", None))
        self.pushButton_6.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Reverse complement", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Paste Query Sequence(s) in CSV or Fasta format", None))
        self.label_15.setText(_translate("MainWindow", "No file selected.", None))
        self.pushButton_9.setText(_translate("MainWindow", "Open File", None))
        self.radioButton_4.setText(_translate("MainWindow", "Convert CSV -> Fasta", None))
        self.radioButton_3.setText(_translate("MainWindow", "Convert Fasta -> CSV", None))
        self.pushButton_7.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Converter", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        self.commandLinkButton.setText(_translate("MainWindow", "Create new database", None))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Delete database", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Databases", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuSequences.setTitle(_translate("MainWindow", "Options", None))
        self.actionClear_all.setText(_translate("MainWindow", "Clear all fields", None))
        self.actionAbout.setText(_translate("MainWindow", "About BlasterQt", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))
        self.actionDocumentation.setToolTip(_translate("MainWindow", "Help", None))
        self.actionConvert_Fasta_Excel.setText(_translate("MainWindow", "Convert  Fasta <-> CSV", None))

import blaster_rc
